# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
warnings_are_errors: true
sudo: required
# build matrix; turn on vdiffr only on r release
matrix:
  include:
  - r: devel
    # avoind errors due to world clock API (hopefully can be removed in future)
    env: _R_CHECK_SYSTEM_CLOCK_=false
  - r: release
    env: VDIFFR_RUN_TESTS=true
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("MaaniBeigy/DescObs")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
  - r: oldrel
  - r: 3.2
    env: R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - r: 3.1
    env: R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # switch off vdiffr by default
  - VDIFFR_RUN_TESTS=false
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgsl-dev texlive libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'
after_success:
  - Rscript -e 'covr::codecov()'
