---
title: "Versatile Exploration of Data: cqv"
author: "Maani Beigy"
date: "February 25, 2019"
output: rmarkdown::html_vignette
bibliography: DescObs.bib
csl: apa.csl
vignette: >
  %\VignetteIndexEntry{cqv}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Coefficient of Quartile Variation   
Coefficient of quartile variation *($CQV$)* is a measure of relative dispersion  that is based on interquartile range (`IQR`). Since *cqv* is unitless, it is 
useful for comparison of variables with different units. It is also a measure of homogeneity [@Bonett2006; @Altunkaynak2018].    
The *population* coefficient of quartile variation is:    
$$
CQV = \biggl(\frac{Q_3-Q_1}{Q_3+Q_1}\biggr)\times100
$$
where $q_3$ and $q_1$ are the population third quartile 
(*i.e.,* $75^{th}$ percentile) and first quartile (*i.e.,* $25^{th}$ percentile), respectively. Almost always, we analyze data from samples but want to 
generalize it as the population's parameter [@Albatineh2014]. Its sample's estimate is given as:    
$$
cqv = \biggl(\frac{q_3-q_1}{q_3+q_1}\biggr)\times100
$$
There are different methods for the calculation of **confidence intervals (CI)** 
for *CQV*. All of them are fruitful and have particular use cases. For sake of versatility, we cover almost all of these methods in `DescObs` package. Here, we explain them along with some examples:     
### Bonett Confidence Interval
Bonett [@Bonett2006] introduced the following confidence interval for *CQV*:   
$$
\exp\{\ln{(D/S)c\  \pm\ Z_{1-\alpha/2}\sqrt{v} }\}
$$
where $c = n/(n-1)$ is a centering adjustment which helps to equalize the tail error probabilities [@Bonett2006; @Altunkaynak2018]. $D = \hat{Q3}-\hat{Q1}$ and
$S = \hat{Q3}+\hat{Q1}$ are the sample $25^{th}$ and $75^{th}$ percentiles, respectively; $Z_{1-\alpha/2}$ is the $1-\alpha/2$ quantile of the standard 
normal distribution.

# References   



